### ISSUE TITLE
Drop shadow on arrows in gallery.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Tal-Dvorski-2nd-Site#3]
![screenshot from 2017-01-30 12-06-36](https://cloud.githubusercontent.com/assets/1911594/22419128/b560c2c8-e6e4-11e6-8235-51ba97f98c7e.png)
Since image in background can not be predicted we need to ensure arrows have sufficient contrast to background. Dropping white shadow or transparent white background for the arrow will provide sufficient contrast.

**Comment by iliyaM** [comment]
background white 0.5 transparent
